name: CommandDelay
author: Enrico
version: 2.0.5
main: me.onenrico.commanddelay.main.Core
description: Command Delay Solution
softdepend: [Vault]
api-version: 1.13
commands:
  commanddelay:
    description: Command for CommandDelay plugin
    usage: /commanddelay help
    aliases: cd